/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Alunos
 */
public class JFrameCadastroCarro extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCadastroCarro
     */
    public JFrameCadastroCarro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelDescricao = new javax.swing.JLabel();
        jLabelFabricante = new javax.swing.JLabel();
        jLabelPlaca = new javax.swing.JLabel();
        jLabelChassi = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabelQuilometragem = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabelPotencia = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabelDataCompra = new javax.swing.JLabel();
        jLabelEsta_funcionando = new javax.swing.JLabel();
        jLabelPermitida_circulacao = new javax.swing.JLabel();
        jLabelQuantidade_portas = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelAno_Lancamento = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabelTipo_Pneu = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox();
        jLabelRenavam = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jTextField9 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField8 = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        jTextField2.setText("jTextField2");

        jTextField7.setText("jTextField7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Codigo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 38, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 46, 32, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Cor");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 84, 27, 15);

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(105, 43, 175, 20);

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(560, 460, 69, 23);

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(460, 460, 83, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 430, 340, 60);

        jLabelDescricao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDescricao.setText("Descriçao");
        getContentPane().add(jLabelDescricao);
        jLabelDescricao.setBounds(100, 400, 110, 20);

        jLabelFabricante.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelFabricante.setText("Fabricante");
        getContentPane().add(jLabelFabricante);
        jLabelFabricante.setBounds(10, 115, 60, 14);

        jLabelPlaca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPlaca.setText("Placa");
        getContentPane().add(jLabelPlaca);
        jLabelPlaca.setBounds(10, 167, 30, 14);

        jLabelChassi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelChassi.setText("Chassi");
        getContentPane().add(jLabelChassi);
        jLabelChassi.setBounds(10, 210, 36, 14);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(105, 207, 175, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(105, 164, 175, 20);

        jLabelQuilometragem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelQuilometragem.setText("Quilometragem");
        getContentPane().add(jLabelQuilometragem);
        jLabelQuilometragem.setBounds(10, 248, 88, 14);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(105, 245, 175, 20);

        jLabelPotencia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPotencia.setText("Potencia");
        getContentPane().add(jLabelPotencia);
        jLabelPotencia.setBounds(10, 286, 49, 14);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(105, 283, 175, 20);

        jLabelDataCompra.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDataCompra.setText("Data da Compra");
        getContentPane().add(jLabelDataCompra);
        jLabelDataCompra.setBounds(327, 46, 91, 14);

        jLabelEsta_funcionando.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelEsta_funcionando.setText("Esta Funcionando");
        getContentPane().add(jLabelEsta_funcionando);
        jLabelEsta_funcionando.setBounds(327, 84, 98, 14);

        jLabelPermitida_circulacao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPermitida_circulacao.setText("Permitida Circulação");
        getContentPane().add(jLabelPermitida_circulacao);
        jLabelPermitida_circulacao.setBounds(327, 115, 116, 14);

        jLabelQuantidade_portas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelQuantidade_portas.setText("Quntidade de Portas");
        getContentPane().add(jLabelQuantidade_portas);
        jLabelQuantidade_portas.setBounds(327, 146, 115, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Quantidade de Batidas");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(327, 175, 127, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Ano de Fabricação");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(327, 210, 103, 14);

        jLabelAno_Lancamento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAno_Lancamento.setText("Ano Lançamento");
        getContentPane().add(jLabelAno_Lancamento);
        jLabelAno_Lancamento.setBounds(330, 250, 90, 14);
        getContentPane().add(jTextField12);
        jTextField12.setBounds(461, 169, 176, 20);

        jLabelTipo_Pneu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTipo_Pneu.setText("Tipo de Pneu");
        getContentPane().add(jLabelTipo_Pneu);
        jLabelTipo_Pneu.setBounds(330, 290, 80, 14);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Branco", "Preto", "Azul", "Vermelho" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(110, 80, 160, 20);
        getContentPane().add(jSpinner1);
        jSpinner1.setBounds(460, 210, 70, 20);
        getContentPane().add(jSpinner2);
        jSpinner2.setBounds(460, 250, 70, 20);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1.setText("Sim");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(470, 110, 47, 23);

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox2.setText("Não");
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(560, 110, 60, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VW", "Chevrolet", "BMW", "Ferrari" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(110, 110, 160, 20);

        jLabelRenavam.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelRenavam.setText("Renavam");
        getContentPane().add(jLabelRenavam);
        jLabelRenavam.setBounds(330, 320, 54, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(460, 320, 180, 20);

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox3.setText("Sim");
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(470, 80, 81, 23);

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox4.setText("Não");
        getContentPane().add(jCheckBox4);
        jCheckBox4.setBounds(560, 80, 47, 23);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(460, 40, 160, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aro 13", "Aro 17", "Aro 18", "Aro 19" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(460, 290, 80, 20);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(110, 10, 170, 20);

        jRadioButton3.setText("2 Portas");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(460, 140, 65, 23);

        jRadioButton4.setText("4 Portas");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(560, 140, 65, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCadastroCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAno_Lancamento;
    private javax.swing.JLabel jLabelChassi;
    private javax.swing.JLabel jLabelDataCompra;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelEsta_funcionando;
    private javax.swing.JLabel jLabelFabricante;
    private javax.swing.JLabel jLabelPermitida_circulacao;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelPotencia;
    private javax.swing.JLabel jLabelQuantidade_portas;
    private javax.swing.JLabel jLabelQuilometragem;
    private javax.swing.JLabel jLabelRenavam;
    private javax.swing.JLabel jLabelTipo_Pneu;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
