/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.CarroDAO;
import database.Utilitarios;
import java.sql.Date;
import javax.swing.JOptionPane;
import model.Carro;

/**
 *
 * @author Alunos
 */
public class JFrameCadastroCarro extends javax.swing.JFrame {
    private Object jFormattedTextFieldDataCompra;



    /**
     * Creates new form JFrameCadastroCarro
     */
    public JFrameCadastroCarro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelCor = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelDescricao = new javax.swing.JLabel();
        jLabelFabricante = new javax.swing.JLabel();
        jLabelPlaca = new javax.swing.JLabel();
        jLabelChassi = new javax.swing.JLabel();
        jTextFieldChassi = new javax.swing.JTextField();
        jTextFieldPlaca = new javax.swing.JTextField();
        jLabelQuilometragem = new javax.swing.JLabel();
        jTextFieldQuilometragem = new javax.swing.JTextField();
        jLabelPotencia = new javax.swing.JLabel();
        jTextFieldPotencia = new javax.swing.JTextField();
        jLabelDataCompra = new javax.swing.JLabel();
        jLabelEstaFuncionando = new javax.swing.JLabel();
        jLabelPermitidaCirculacao = new javax.swing.JLabel();
        jLabelQtdPortas = new javax.swing.JLabel();
        jLabelQtdBatidas = new javax.swing.JLabel();
        jLabelAnoFabricacao = new javax.swing.JLabel();
        jLabelAnoLancamento = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabelTipoPneu = new javax.swing.JLabel();
        jComboBoxCor = new javax.swing.JComboBox();
        jSpinnerAnoFabricacao1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jComboBoxFabricante = new javax.swing.JComboBox();
        jLabelRenavam = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextFieldDataCompra = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField8 = new javax.swing.JTextField();
        jRadioButtonQtdPortas2 = new javax.swing.JRadioButton();
        jRadioButtonQtdPortas4 = new javax.swing.JRadioButton();
        jRadioButtonEstaFuncionalSim = new javax.swing.JRadioButton();
        jRadioButtonEstaFuncionalNao = new javax.swing.JRadioButton();

        jTextField2.setText("jTextField2");

        jTextField7.setText("jTextField7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Codigo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 38, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 46, 32, 14);

        jLabelCor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCor.setText("Cor");
        getContentPane().add(jLabelCor);
        jLabelCor.setBounds(10, 84, 27, 15);

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(105, 43, 175, 20);

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(560, 460, 69, 23);

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(460, 460, 83, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 430, 340, 60);

        jLabelDescricao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDescricao.setText("Descriçao");
        getContentPane().add(jLabelDescricao);
        jLabelDescricao.setBounds(100, 400, 110, 20);

        jLabelFabricante.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelFabricante.setText("Fabricante");
        getContentPane().add(jLabelFabricante);
        jLabelFabricante.setBounds(10, 115, 60, 14);

        jLabelPlaca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPlaca.setText("Placa");
        getContentPane().add(jLabelPlaca);
        jLabelPlaca.setBounds(10, 167, 30, 14);

        jLabelChassi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelChassi.setText("Chassi");
        getContentPane().add(jLabelChassi);
        jLabelChassi.setBounds(10, 210, 36, 14);
        getContentPane().add(jTextFieldChassi);
        jTextFieldChassi.setBounds(105, 207, 175, 20);
        getContentPane().add(jTextFieldPlaca);
        jTextFieldPlaca.setBounds(105, 164, 175, 20);

        jLabelQuilometragem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelQuilometragem.setText("Quilometragem");
        getContentPane().add(jLabelQuilometragem);
        jLabelQuilometragem.setBounds(10, 248, 88, 14);
        getContentPane().add(jTextFieldQuilometragem);
        jTextFieldQuilometragem.setBounds(105, 245, 175, 20);

        jLabelPotencia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPotencia.setText("Potencia");
        getContentPane().add(jLabelPotencia);
        jLabelPotencia.setBounds(10, 286, 49, 14);
        getContentPane().add(jTextFieldPotencia);
        jTextFieldPotencia.setBounds(105, 283, 175, 20);

        jLabelDataCompra.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDataCompra.setText("Data da Compra");
        getContentPane().add(jLabelDataCompra);
        jLabelDataCompra.setBounds(327, 46, 91, 14);

        jLabelEstaFuncionando.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelEstaFuncionando.setText("Esta Funcionando");
        getContentPane().add(jLabelEstaFuncionando);
        jLabelEstaFuncionando.setBounds(327, 84, 98, 14);

        jLabelPermitidaCirculacao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPermitidaCirculacao.setText("Permitida Circulação");
        getContentPane().add(jLabelPermitidaCirculacao);
        jLabelPermitidaCirculacao.setBounds(327, 115, 116, 14);

        jLabelQtdPortas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelQtdPortas.setText("Quntidade de Portas");
        getContentPane().add(jLabelQtdPortas);
        jLabelQtdPortas.setBounds(327, 146, 115, 14);

        jLabelQtdBatidas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelQtdBatidas.setText("Quantidade de Batidas");
        getContentPane().add(jLabelQtdBatidas);
        jLabelQtdBatidas.setBounds(327, 175, 127, 14);

        jLabelAnoFabricacao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAnoFabricacao.setText("Ano de Fabricação");
        getContentPane().add(jLabelAnoFabricacao);
        jLabelAnoFabricacao.setBounds(327, 210, 103, 14);

        jLabelAnoLancamento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAnoLancamento.setText("Ano Lançamento");
        getContentPane().add(jLabelAnoLancamento);
        jLabelAnoLancamento.setBounds(330, 250, 90, 14);
        getContentPane().add(jTextField12);
        jTextField12.setBounds(461, 169, 176, 20);

        jLabelTipoPneu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTipoPneu.setText("Tipo de Pneu");
        getContentPane().add(jLabelTipoPneu);
        jLabelTipoPneu.setBounds(330, 290, 80, 14);

        jComboBoxCor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Branco", "Preto", "Azul", "Vermelho" }));
        jComboBoxCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCorActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCor);
        jComboBoxCor.setBounds(110, 80, 160, 20);
        getContentPane().add(jSpinnerAnoFabricacao1);
        jSpinnerAnoFabricacao1.setBounds(460, 210, 70, 20);
        getContentPane().add(jSpinner2);
        jSpinner2.setBounds(460, 250, 70, 20);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1.setText("Sim");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(470, 110, 47, 23);

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox2.setText("Não");
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(560, 110, 60, 23);

        jComboBoxFabricante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VW", "Chevrolet", "BMW", "Ferrari" }));
        getContentPane().add(jComboBoxFabricante);
        jComboBoxFabricante.setBounds(110, 110, 160, 20);

        jLabelRenavam.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelRenavam.setText("Renavam");
        getContentPane().add(jLabelRenavam);
        jLabelRenavam.setBounds(330, 320, 54, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(460, 320, 180, 20);

        jTextFieldDataCompra.setToolTipText("21/08/2017");
        getContentPane().add(jTextFieldDataCompra);
        jTextFieldDataCompra.setBounds(460, 40, 160, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aro 13", "Aro 17", "Aro 18", "Aro 19" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(460, 290, 80, 20);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(110, 10, 170, 20);

        jRadioButtonQtdPortas2.setText("2 Portas");
        getContentPane().add(jRadioButtonQtdPortas2);
        jRadioButtonQtdPortas2.setBounds(470, 140, 65, 23);

        jRadioButtonQtdPortas4.setText("4 Portas");
        getContentPane().add(jRadioButtonQtdPortas4);
        jRadioButtonQtdPortas4.setBounds(560, 140, 65, 23);

        jRadioButtonEstaFuncionalSim.setText("Sim");
        getContentPane().add(jRadioButtonEstaFuncionalSim);
        jRadioButtonEstaFuncionalSim.setBounds(470, 80, 90, 23);

        jRadioButtonEstaFuncionalNao.setText("Não");
        jRadioButtonEstaFuncionalNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEstaFuncionalNaoActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonEstaFuncionalNao);
        jRadioButtonEstaFuncionalNao.setBounds(560, 80, 120, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jComboBoxCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCorActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        Carro meuCarro = new Carro();
        meuCarro.setNome(jTextFieldNome.getText());
        meuCarro.setAnoFabricacao(Short.parseShort(jSpinnerAnoFabricacao1.getValue().toString()));
        
        meuCarro.setFabricante(String.valueOf(jComboBoxFabricante.getSelectedItem()));
        //21/08/2017
        String dataCompra = jFormattedTextFieldDataCompra.getText();
        int ano = Integer.parseInt(dataCompra.substring(6, 10));
        int mes = Integer.parseInt(dataCompra.substring(3, 5));
        int dia = Integer.parseInt(dataCompra.substring(0, 2));
        meuCarro.setDataCompra(new Date(ano, mes, dia));
        
        byte quantidadePortas = jRadioButtonQtdPortas2.isSelected() ?(byte)2:(byte)4;
        meuCarro.setQuantidadePortas(quantidadePortas);
        meuCarro.setEstaFuncional(jRadioButtonEstaFuncionalSim.isSelected());
        
        CarroDAO dao = new CarroDAO();
        int codigo = dao.inserir(meuCarro);
        if(codigo!= Utilitarios.NAO_FOI_POSSIVEL_INSERIR){
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");
        }else{
            JOptionPane.showMessageDialog(null, "Não foi possível inserir");
        }
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jRadioButtonEstaFuncionalNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEstaFuncionalNaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonEstaFuncionalNaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCadastroCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBoxCor;
    private javax.swing.JComboBox jComboBoxFabricante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAnoFabricacao;
    private javax.swing.JLabel jLabelAnoLancamento;
    private javax.swing.JLabel jLabelChassi;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelDataCompra;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelEstaFuncionando;
    private javax.swing.JLabel jLabelFabricante;
    private javax.swing.JLabel jLabelPermitidaCirculacao;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelPotencia;
    private javax.swing.JLabel jLabelQtdBatidas;
    private javax.swing.JLabel jLabelQtdPortas;
    private javax.swing.JLabel jLabelQuilometragem;
    private javax.swing.JLabel jLabelRenavam;
    private javax.swing.JLabel jLabelTipoPneu;
    private javax.swing.JRadioButton jRadioButtonEstaFuncionalNao;
    private javax.swing.JRadioButton jRadioButtonEstaFuncionalSim;
    private javax.swing.JRadioButton jRadioButtonQtdPortas2;
    private javax.swing.JRadioButton jRadioButtonQtdPortas4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinnerAnoFabricacao1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextFieldChassi;
    private javax.swing.JTextField jTextFieldDataCompra;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPlaca;
    private javax.swing.JTextField jTextFieldPotencia;
    private javax.swing.JTextField jTextFieldQuilometragem;
    // End of variables declaration//GEN-END:variables
}
